data_locale = """healthWarning: 'Данный продукт не является безвредным и вызывает зависимость.',
            heetsDisclaimer: 'Табачные стики - нагреваемые табачные палочки.',
            footerDisclaimer: 'Данный продукт не является безвредным и содержит никотин, который вызывает зависимость. Только для использования лицами, достигшими возраста 21 года и старше, желающими продолжать курить или использовать никотинсодержащую продукцию.',
            footerLinks: 'Полезные ссылки',
            footerSupport: 'Поддержка',
            footerDocs: 'Документы',
            footerFeedback: 'Связаться с нами',
            footerLink1: 'Регистрация устройств',
            footerLink2: 'Найти магазин',
            footerLink3: 'Новости',
            footerLink4: 'Калькулятор доставки',
            footerLink5: 'Перейти на PMI.com',
            footerSupport1: 'Вопросы и ответы',
            footerDoc1: 'Уведомление о соблюдении конфиденциальности',
            footerDoc2: 'Условия использования веб-сайта',
            footerDoc3: 'Согласие на сбор и обработку персональных данных',
            footerDoc4: 'Публичная оферта',
            footerDoc5: 'Условия доставки',
            footerDoc6: 'Уведомление об использовании файлов Cookie',
            footerDoc7: 'Посмотреть все документы',
            footerHelp1: 'Уведомление о соблюдении конфиденциальности',
            footerHelp2: 'Уведомление о соблюдении конфиденциальности',
            footerHelp3: 'Уведомление о соблюдении конфиденциальности',
            footerHelp4: 'Уведомление о соблюдении конфиденциальности',
            footerModal1: 'Уведомление о соблюдении конфиденциальности',
            footerModal2: 'Условия использования веб-сайта',
            footerModal3: 'Согласие на сбор и обработку персональных данных',
            footerModal4: 'Условия программы',
            headerLink1: 'Все об IQOS',
            headerLink2: 'Тест-драйв',
            headerLink3: 'Купить',
            headerLink4: 'Помощь',
            headerLink5: 'Новости',
            headerLink6: 'Дарите скидки',
            headerLink7: 'IQOS+',
            notFoundTitle: 'Кажется, такой страницы не существует',
            notFoundDesc1: 'НО ЕСТЬ',
            notFoundDesc2: 'КАТАЛОГ',
            notFoundDesc3: ', ГДЕ МОЖНО ПОДОБРАТЬ СЕБЕ ЧТО-НИБУДЬ ИНТЕРЕСНОЕ',
            supportHelper: 'Свяжитесь с нами, если у вас есть вопросы по регистрации',
            supportTitle1: 'Онлайн-чат на сайте',
            supportTitle2: 'Поддержка IQOS по телефону',
            supportTitle3: 'IQOS в Telegram',
            supportTitle4: 'IQOS на Facebook',
            supportDesc1: 'Поговорите с одним из наших экспертов',
            supportDesc2: 'Позвоните нам с мобильного телефона по номеру',
            supportDesc3: 'Свяжитесь со службой поддержки IQOS в Telegram',
            supportDesc4: 'Посетите нашу официальную страницу IQOS на Facebook',
            supportAction1: 'Начать',
            supportAction2: '2121',
            supportAction3: 'IQOSKZ_Support_bot',
            supportAction4: 'IQOS Казахстан',
            benefitsBtn: 'Зарегистрироваться',
            benefitsTitle1: 'Замена по <br>негарантийным случаям',
            benefitsDesc1: 'Если неисправность вашего устройства IQOS не является гарантийным случаем, вы вправе обратиться с просьбой его замены один раз в течение гарантийного срока.',
            benefitsTitle2: 'Международная <br>поддержка',
            benefitsDesc2: 'Если вы находитесь за рубежом, вы сможете обратиться на линию международной поддержки для замены устройства в течение гарантийного срока.',
            benefitsTitle3: 'Персональный <br>консультант',
            benefitsDesc3: 'Помощь Службы поддержки в удобном для вас канале коммуникации',
            iinTitle: 'Регистрация пользователей IQOS, достигших 21 года и более',
            iinDesc: 'Пожалуйста, введите ваш ИИН для подтверждения соотвествия вашего возраста требованиям законодательства РК.',
            iinLabel: 'ИИН',
            iinErrorRegistered: 'Данный ИИН уже зарегистрирован.',
            iinErrorInvalid: 'Невалидный ИИН',
            iinErrorUnregistered: 'Данный ИИН не зарегистрирован.',
            iinErrorEmpty: 'Пожалуйста, введите ваш ИИН.',
            iinErrorLength: 'ИИН должен быть 12 символов.',
            smsAuthTitle: 'Отправить код подтверждения на номер ',
            smsAuthDesc: 'Свяжитесь со службой поддержки, если номер некорректный.',
            smsAuthBtn: 'Выслать код на телефон',
            smsAuthTitle2: 'Мы отправили проверочный код на номер ',
            smsAuthDesc2: 'Свяжитесь со службой поддержки, если номер некорректный.',
            smsAuthDesc3: 'Если указанный номер некорректный, пожалуйста, свяжитесь со службой поддержки IQOS.',
            smsAuthLabel: 'Введите код подтверждения из SMS',
            smsAuthErrorWrong: 'Неверный код подтверждения.',
            smsAuthErrorEmpty: 'Пожалуйста, введите код подтверждения.',
            smsAuthErrorLength: 'Код подтверждения должен быть 6 символов.',
            registrationTitle: 'Регистрация',
            userErrorRegistered: 'Пользователь уже зарегистрирован',
            emailLabel: 'E-mail',
            emailErrorCyrillic: 'Email может состоять только из латинских букв.',
            emailErrorEmpty: 'Пожалуйста, введите ваш E-mail.',
            emailErrorFormat: 'Пожалуйста, введите email в формате "example@mail.kz"',
            phoneLabel: 'Мобильный телефон',
            phoneErrorFormat: 'Пожалуйста, введите телефон в верном формате',
            phoneErrorEmpty: 'Пожалуйста, введите номер мобильного телефона.',
            nameLabel: 'Имя',
            lastNameLabel: 'Фамилия',
            dateLabel: 'Дата рождения',
            genderLabel: 'Пол',
            cityLabel: 'Город',
            langLabel: 'Язык коммуникации',
            refferalLabel: 'Реферальный код',
            refferalMessages: 'Если у Вас есть реферальный код, введите его здесь',
            male: 'Мужской',
            female: 'Женский',
            consentTitle: 'Мы отправим проверочный код на номер<br>указанный вами при регистрации: ',
            consentDesc: 'Убедитесь, что номер мобильного телефона введен верно - на него будет отправлен код',
            consentAlert: 'Отправьте полученный по СМС код <strong>обратно на номер 2121</strong> с вашего номера телефона',
            consentDocs: 'Отправив СМС, вы подтверждаете своё согласие со:',
            consentDoc1: 'сбором и обработкой персональных данных',
            consentDoc2: 'условиями вебсайта',
            consentDoc3: 'условиями программы',
            consentSendBtn: 'Выслать код на телефон',
            consentTitle2: 'Подтверждение номера телефона',
            consentDesc2: 'Мы отправили вам код подтверждения на номер',
            consentWait: 'Ожидание кода',
            consentRepeat1: 'Вы сможете отправить код повторно через',
            consentRepeat2: 'секунд.',
            consentRepeat3: 'Вы можете отправить код',
            consentRepeat4: 'повторно',
            iinRegTitle: 'Подтверждение ИНН',
            iinRegLabel: 'ИНН',
            devicesTitle: 'Ваши устройства',
            addDeviceTitle: 'Регистрация <br>вашего устройства',
            addDeviceTitle2: 'Регистрация вашего устройства',
            codentifyLabel: 'Код устройства',
            errorDeviceNotFound: 'Устройство не найдено',
            errorDeviceRegistered: 'Устройство уже зарегистрировано',
            errorDeviceEmpty: 'Пожалуйста, введите код устройства.',
            errorDeviceLength: 'Код устройства должен быть не менее 12 символов.',
            howToTitle: 'Как его найти?',
            howTo1: 'Вы можете ввести код с держателя',
            howTo2: 'или с зарядного устройства',
            howTo3: 'или с упаковочной коробки',
            warranty: 'Гарантия на устройство действует до',
            warranty2: '{0} дней',
            warranty3: 'Гарантийный срок<br>истекает через',
            moreInfo: 'Подробнее',
            charger: 'Зарядное устройство',
            holder: 'Держатель',
            kit: 'Упаковочная коробка',
            missing: 'Отсутствует',
            successTitle: 'Устройство успешно зарегистрировано',
            successTitle2: 'Примеры применения вашего ваучера',
            successSubtitle: ', Вы получили ваучер на 2000 тг!',
            successDesc: 'На любые товары в магазинах IQOS и на сайте IQOS.com.',
            successDesc2: 'Запомните код, скопируйте в записки или сохраните как изображение',
            successLinksTitle: 'Полезные ссылки',
            successLink1: 'Купить HEETS с доставкой',
            successLink2: 'Дарите скидки друзьям',
            successLink3: 'Как пользоваться IQOS',
            successLink4: 'Добавить устройства',
            tradeInCongrats: 'поздравляем!',
            tradeInDesc: 'Ваш ваучер на скидку для покупки нового IQOS 3 DUO по цене <strong>{0}</strong> тг.',
            tradeInDetails: 'Вы также получите ваучер по СМС на указанный номер.',
            tradeInBtn: 'Перейти в магазин',
            tradeInSteps: 'Следующие шаги',
            tradeInStep1: 'Перейдите в каталог и оформите заказ на IQOS 3 DUO / IQOS 3 DUO Holder, применив ваучер на скидку.',
            tradeInStep2: 'Передайте ваше устройство курьеру при <span style="text-decoration:underline; font-weight:bold;">доставке</span> нового устройства.',
            tradeInStep3: 'Остались вопросы? Свяжитесь со Службой Поддержки по номеру <a style="text-decoration:none; font-weight: bold; color:black; font-weight:bold;" href="tel:2121">2121</a>.',
            back: 'Назад',
            next: 'Дальше',
            errorUnexpected: 'Что-то пошло не так. Пожалуйста, повторите позже.',
            errorRequired: 'Поле обязательно для заполнения.',
            errorWrongAuth: 'Неправильный логин/пароль',
            russian: 'Русский',
            kazakh: 'Казахский',
            english: 'Английский',
            copied: 'Код <strong>{0}</strong> скопирован!',
            buy: 'Купить',
            tenge: 'тг.',
            yes: 'да',
            no: 'нет',
            iinErrorBelowAge: 'Чтобы получить доступ к данному сайту, Вам должно быть 21 и более лет.',
            close: 'Закрыть',
            register: 'Зарегистрировать',
            goldTitle: 'Зарегистрируйте ваше устройство и получите ваучер на 2000 тг. на покупки в магазинах IQOS и на сайте IQOS.com',
            tradeInValidateTitle: 'Ваша цена на <div><nobr>IQOS 3 DUO:</nobr>',
            tradeInValidateBtn: 'Принять участие в Trade-In',
            successMessage1: '{0}, спасибо! <br>Ваше устройство зарегистрировано.',
            successMessage2: 'За регистрацию устройства вам будет отправлен ваучер RE-********** по смс <nobr>на номер <b>{0}</b></nobr>, который вы указывали при регистрации. Ваучер дает скидку <b style="white-space: nowrap;">2000 тг.</b> на любые доступные товары в официальных магазинах IQOS и на <a target="_blank" href="https://kzstg.iqos.com">IQOS.COM</a>.',
            fbTitle: 'Преимущества регистрации',
            fbBenefit1: 'Получите ваучер на 2 000 тенге на покупки в магазинах IQOS и на сайте iqos.com',
            fbBenefit2: 'Замена по негарантийным случаям',
            fbBenefit3: 'Дарите скидки друзьям и получайте бонусы для себя',
            fbBenefit4: 'Участвуйте в программе Trade in - новый IQOS 3 DUO со скидкой',
            fbBenefit5: 'Закажите IQOS онлайн с бесплатной доставкой до вашего города',
            fbBenefit6: 'Пишите Службе поддержки где и когда вам удобно',
            fbBenefit7: 'Узнавайте о всех новостях, специальных предложениях и предзаказах.',
            step1: 'Проверка ИИН',
            step2: 'Регистрация',
            step3: 'Регистрация устройств',
            stepReg: 'Регистрация',
            stepAuth: 'Подтверждение по СМС',"""

data = data_locale.split('\n')
all = []
for i in data:
    i = i.strip().split("'")
    try:
        i.remove(',')
    except:
        pass

    all.append(i)
file = open('test3.txt', 'w', encoding='utf-8')
for i in all:
    file.write('"'+i[0]+'"'+': '+'"'+i[1]+'"'+',\n')
file.close()
